name: Run Curl Command

on:
  push:
    branches:
      - qa

jobs:
  execute-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Execute Curl Command
        run: |
          curl -X POST "https://elastic.snaplogic.com/api/1/rest/public/assetapi/project/Partners/Nihilent/snaplogic-user-test123" \
               -u "vilas.wagh@nihilent.com:Vilas@123" \
               -H "Content-Type: application/json" \
               -d '{
                     "permissions": [
                       {
                         "perms": ["R", "W"],
                         "subject_type": "USER",
                         "inherit": true,
                         "subject": "vilas.wagh@nihilent.com"
                       }
                     ]
                   }'
