on:
  push:
    branches:
      - dev
      - qa
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Test
      run: echo "Test is completed"
      
  qa-promotion:
    if: github.ref == 'refs/heads/qa'
    needs: test
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up environment variables
      run: |
        echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
        echo "PASS=${{ secrets.PASS }}" >> $GITHUB_ENV
        echo "URL=${{ vars.URL }}" >> $GITHUB_ENV
        echo "ORG=${{ vars.ORG }}" >> $GITHUB_ENV
        echo "PROJECT_SPACE_QA=${{ vars.PROJECT_SPACE_QA }}" >> $GITHUB_ENV
        echo "PROJECT_QA=${{ vars.PROJECT_QA }}" >> $GITHUB_ENV
        echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
        
    - name: Create QA Project
      id: create-qa-project
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${URL}/api/1/rest/public/assetapi/project/${ORG}/${PROJECT_SPACE_QA}/${PROJECT_QA}" \
        -u "${USER}:${PASS}" \
        -H "Content-Type: application/json" \
        -d "{\"permissions\":[{\"perms\": [\"R\",\"W\",\"X\"],\"subject_type\": \"USER\",\"inherit\": true,\"subject\": \"${USER}\"}]}" \
        --trace-ascii /dev/stdout)
        if [ "$response" = "409" ]; then
          echo "status=conflict" >> $GITHUB_OUTPUT
        else
          echo "status=created" >> $GITHUB_OUTPUT
        fi
        
    - name: Handle Conflict
      if: steps.create-qa-project.outputs.status == 'conflict'
      run: echo "The asset conflicts with an existing asset, so cannot create."
      
    - name: Checkout Code to QA
      if: steps.create-qa-project.outputs.status == 'created' || steps.create-qa-project.outputs.status == 'conflict'
      run: |
        curl -X POST "${URL}/api/1/rest/public/project/checkout/${ORG}/${PROJECT_SPACE_QA}/${PROJECT_QA}" \
        -u "${USER}:${PASS}" \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"${REPO_NAME}\",\"ref\":\"${BRANCH_NAME}\"}" \
        --trace-ascii /dev/stdout
