name: Run Curl Command

on:
  push:
    branches:
      - qa

jobs:
  execute-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Execute Curl Command to Create Project
        id: create-qa-project
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://elastic.snaplogic.com/api/1/rest/public/assetapi/project/Partners/Nihilent/snaplogic-user-test124" \
          -u "sanghamitra.pattanayak@nihilent.com:Nihilent@123" -H "Content-Type: application/json" \
          -d '{
                "permissions": [
                  {
                    "perms": ["R", "W", "A", "X"],
                    "subject_type": "USER",
                    "inherit": true,
                    "subject": "sanghamitra.pattanayak@nihilent.com"
                  }
                ]
              }')

          if [ "$response" = "409" ]; then
            echo "::set-output name=status::conflict"
          else
            echo "::set-output name=status::created"
          fi

      - name: Handle Conflict
        if: steps.create-qa-project.outputs.status == 'conflict'
        run: |
          echo "The asset conflicts with an existing asset, so cannot create."
          # Add any additional tasks to handle the conflict here
